name: General CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  
  build_normal:
    runs-on: ubuntu-latest
    steps:
    - name: Prerequisites 
      run: sudo apt install -y build-essential wget help2man libncurses5-dev libtool libtool-bin
    - uses: actions/checkout@v3
    - name: Make toolchain
      run: ./build.sh
    - name: Bundle toolchain
      run: cd output; tar -cjf ../$(echo *).tar.xz *
    - name: Upload toolchain
      uses: actions/upload-artifact@v4
      with:
        name: x86-64_glibc
        path: *.tar.xz
